const D=window.DISTRIBUTIONS||[
{name:"Bernoulli",type:"Discrete",params:"p",key:"bernoulli"},{name:"Binomial",type:"Discrete",params:"n,p",key:"binomial"},
{name:"Geometric",type:"Discrete",params:"p",key:"geometric"},{name:"Negative Binomial",type:"Discrete",params:"r,p",key:"negbin"},
{name:"Hypergeometric",type:"Discrete",params:"N,K,n",key:"hyper"},{name:"Poisson",type:"Discrete",params:"lambda",key:"poisson"},
{name:"Discrete Uniform",type:"Discrete",params:"a,b",key:"duniform"},{name:"Categorical",type:"Discrete",params:"p1,p2,p3",key:"categorical"},
{name:"Multinomial",type:"Discrete",params:"n,p1,p2,p3",key:"multinomial"},{name:"Zipf",type:"Discrete",params:"s",key:"zipf"},
{name:"Logarithmic",type:"Discrete",params:"p",key:"logarithmic"},{name:"Skellam",type:"Discrete",params:"mu1,mu2",key:"skellam"},
{name:"Discrete Laplace",type:"Discrete",params:"p",key:"dlaplace"},{name:"Beta-Binomial",type:"Discrete",params:"n,alpha,beta",key:"betabin"},
{name:"Dirichlet-Multinomial",type:"Discrete",params:"n,a1,a2,a3",key:"dirichletmulti"},{name:"Borel",type:"Discrete",params:"lambda",key:"borel"},
{name:"Yule-Simon",type:"Discrete",params:"rho",key:"yulesimon"},{name:"Benford",type:"Discrete",params:"base",key:"benford"},
{name:"Bivariate Poisson",type:"Discrete",params:"l1,l2,l3",key:"bipoisson"},{name:"Chinese Restaurant Process",type:"Discrete",params:"alpha,n",key:"crp"},
{name:"Uniform",type:"Continuous",params:"a,b",key:"uniform"},{name:"Normal",type:"Continuous",params:"mu,sigma",key:"normal"},
{name:"Exponential",type:"Continuous",params:"lambda",key:"exponential"},{name:"Gamma",type:"Continuous",params:"shape,scale",key:"gamma"},
{name:"Beta",type:"Continuous",params:"alpha,beta",key:"beta"},{name:"Weibull",type:"Continuous",params:"shape,scale",key:"weibull"},
{name:"Lognormal",type:"Continuous",params:"mu,sigma",key:"lognormal"},{name:"Cauchy",type:"Continuous",params:"x0,gamma",key:"cauchy"},
{name:"Student's t",type:"Continuous",params:"df",key:"t"},{name:"F",type:"Continuous",params:"df1,df2",key:"f"},
{name:"Chi-Square",type:"Continuous",params:"df",key:"chisq"},{name:"Logistic",type:"Continuous",params:"mu,s",key:"logistic"},
{name:"Laplace",type:"Continuous",params:"mu,b",key:"laplace"},{name:"Pareto",type:"Continuous",params:"xm,alpha",key:"pareto"},
{name:"Rayleigh",type:"Continuous",params:"sigma",key:"rayleigh"},{name:"Gumbel",type:"Continuous",params:"mu,beta",key:"gumbel"},
{name:"Triangular",type:"Continuous",params:"a,m,b",key:"triangular"},{name:"Erlang",type:"Continuous",params:"k,lambda",key:"erlang"},
{name:"Inverse Gaussian",type:"Continuous",params:"mu,lambda",key:"invgauss"},{name:"Fisher's z",type:"Continuous",params:"z,df",key:"fisherz"}];

function menuInit(){const b=document.querySelector(".menu-btn"),m=document.querySelector(".menu");if(!b||!m)return;b.onclick=(e)=>{e.stopPropagation();m.classList.toggle("open")};document.addEventListener("click",e=>{if(!m.contains(e.target)&&e.target!==b)m.classList.remove("open")})}menuInit();

function nums(v){return v.split(",").map(Number).filter(Number.isFinite)} function mean(a){return a.reduce((s,x)=>s+x,0)/a.length}
function median(a){a=[...a].sort((x,y)=>x-y);return a.length%2?a[(a.length-1)/2]:(a[a.length/2-1]+a[a.length/2])/2}
function sd(a){let m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}
function calcDesc(){let el=document.getElementById("data");if(!el)return;let a=nums(el.value);if(a.length<2)return;let s=sd(a);document.getElementById("descResult").innerHTML=`<div class="result-grid"><div class="result-box"><span>n</span><strong>${a.length}</strong></div><div class="result-box"><span>Mean</span><strong>${mean(a).toFixed(5)}</strong></div><div class="result-box"><span>Median</span><strong>${median(a).toFixed(5)}</strong></div><div class="result-box"><span>Sample SD</span><strong>${s.toFixed(5)}</strong></div></div>`}

function logGamma(z){const g=7,C=[0.9999999999998099,676.5203681218851,-1259.1392167224028,771.3234287776531,-176.6150291621406,12.507343278686905,-0.13857109526572012,9.984369578019572e-6,1.5056327351493116e-7];if(z<.5)return Math.log(Math.PI)-Math.log(Math.sin(Math.PI*z))-logGamma(1-z);z-=1;let x=C[0];for(let i=1;i<C.length;i++)x+=C[i]/(z+i);let t=z+g+.5;return .5*Math.log(2*Math.PI)+(z+.5)*Math.log(t)-t+Math.log(x)}
function gamma(z){return Math.exp(logGamma(z))} function logChoose(n,k){if(k<0||k>n)return -Infinity;return logGamma(n+1)-logGamma(k+1)-logGamma(n-k+1)}
function erf(x){let s=x<0?-1:1;x=Math.abs(x);let a1=.254829592,a2=-.284496736,a3=1.421413741,a4=-1.453152027,a5=1.061405429,p=.3275911,t=1/(1+p*x);return s*(1-(((((a5*t+a4)*t+a3)*t+a2)*t+a1)*t)*Math.exp(-x*x))}
function normalPdf(x,m,s){return Math.exp(-.5*((x-m)/s)**2)/(s*Math.sqrt(2*Math.PI))} function normalCdf(x,m,s){return .5*(1+erf((x-m)/(s*Math.sqrt(2))))}
function simpson(f,a,b,n=800){if(b<=a)return 0;if(n%2)n++;let h=(b-a)/n,sum=f(a)+f(b);for(let i=1;i<n;i++)sum+=(i%2?4:2)*f(a+i*h);return sum*h/3}
function betaFunc(a,b){return Math.exp(logGamma(a)+logGamma(b)-logGamma(a+b))} let FAST_MATH=false;
function integrateCDF(pdf,x,lo){
if(FAST_MATH)return 0;if(!Number.isFinite(x))return x>0?1:0;let a=lo,b=x;if(b<=a)return 0;return Math.min(1,Math.max(0,simpson(pdf,a,b,700)))}
function poissonPmf(k,l){if(k<0||Math.floor(k)!=k)return 0;return Math.exp(-l+k*Math.log(l)-logGamma(k+1))}
function binomPmf(k,n,p){if(k<0||k>n||Math.floor(k)!=k)return 0;return Math.exp(logChoose(n,k)+k*Math.log(p)+(n-k)*Math.log(1-p))}
function geometricPmf(k,p){return k<1?0:p*Math.pow(1-p,k-1)} function negbinPmf(k,r,p){if(k<0||Math.floor(k)!=k)return 0;return Math.exp(logChoose(k+r-1,k)+r*Math.log(p)+k*Math.log(1-p))}
function betaPdf(x,a,b){return x<=0||x>=1?0:Math.pow(x,a-1)*Math.pow(1-x,b-1)/betaFunc(a,b)}
function gammaPdf(x,k,theta){return x<0?0:Math.pow(x,k-1)*Math.exp(-x/theta)/(gamma(k)*Math.pow(theta,k))}
function tPdf(x,v){return gamma((v+1)/2)/(Math.sqrt(v*Math.PI)*gamma(v/2))*Math.pow(1+x*x/v,-(v+1)/2)}
function fPdf(x,d1,d2){if(x<=0)return 0;return Math.sqrt(Math.pow(d1*x,d1)*Math.pow(d2,d2)/Math.pow(d1*x+d2,d1+d2))/x/betaFunc(d1/2,d2/2)}
const defaults={p:.35,n:10,r:4,N:30,K:12,lambda:3,a:0,b:1,p1:.2,p2:.3,p3:.5,s:2,mu1:4,mu2:2,alpha:2,beta:3,a1:2,a2:3,a3:4,base:10,z:1,df:10,df1:8,df2:12,shape:2,scale:2,mu:0,sigma:1,x0:0,gamma:1,xm:1,rho:3,k:4,m:1};
function distSpec(){let q=new URLSearchParams(location.search).get("name");return D.find(d=>d.name.toLowerCase()===String(q||"Normal").toLowerCase())||D.find(d=>d.name==="Normal")}
function getParams(){let o={};document.querySelectorAll("#fields input[data-p]").forEach(i=>o[i.dataset.p]=Number(i.value));return o}
function besseli(n,z){let sum=0;for(let k=0;k<60;k++){let term=Math.pow(z/2,2*k+n)/(gamma(k+1)*gamma(k+n+1));sum+=term;if(Math.abs(term)<1e-14*Math.max(1,sum))break}return sum}

function calcCore(k,x,p){
const q=p.p??0;
switch(k){
case"bernoulli":return{v:x===1?q:x===0?1-q:0,c:x<0?0:x<1?1-q:1,m:q,vv:q*(1-q),range:[-0.1,1.1],discrete:true};
case"binomial":{let n=Math.round(p.n),v=binomPmf(Math.round(x),n,q),c=0;for(let i=0;i<=Math.floor(x);i++)c+=binomPmf(i,n,q);return{v,c:Math.min(1,c),m:n*q,vv:n*q*(1-q),range:[0,n],discrete:true}}
case"geometric":{let kx=Math.floor(x),v=geometricPmf(kx,q),c=kx<1?0:1-Math.pow(1-q,kx);return{v,c,m:1/q,vv:(1-q)/(q*q),range:[1,Math.max(10,Math.ceil(8/q))],discrete:true}}
case"poisson":{let l=p.lambda,kx=Math.floor(x),v=poissonPmf(kx,l),c=0;for(let i=0;i<=kx;i++)c+=poissonPmf(i,l);return{v,c,m:l,vv:l,range:[0,Math.max(10,Math.ceil(l+6*Math.sqrt(l)))],discrete:true}}
case"uniform":{let a=p.a,b=p.b,v=x>=a&&x<=b?1/(b-a):0,c=x<=a?0:x>=b?1:(x-a)/(b-a);return{v,c,m:(a+b)/2,vv:(b-a)**2/12,range:[a,b],discrete:false}}
case"normal":{let m=p.mu,s=p.sigma;return{v:normalPdf(x,m,s),c:normalCdf(x,m,s),m,vv:s*s,range:[m-4*s,m+4*s],discrete:false}}
case"exponential":{let l=p.lambda,v=x<0?0:l*Math.exp(-l*x),c=x<0?0:1-Math.exp(-l*x);return{v,c,m:1/l,vv:1/(l*l),range:[0,Math.max(5/l,5)],discrete:false}}
case"gamma":{let k=p.shape,th=p.scale,v=gammaPdf(x,k,th),c=integrateCDF(z=>gammaPdf(z,k,th),x,0);return{v,c,m:k*th,vv:k*th*th,range:[0,k*th+6*Math.sqrt(k*th*th)],discrete:false}}
case"beta":{let a=p.alpha,b=p.beta,v=betaPdf(x,a,b),c=integrateCDF(z=>betaPdf(z,a,b),x,0),m=a/(a+b),vv=a*b/((a+b)**2*(a+b+1));return{v,c,m,vv,range:[0,1],discrete:false}}
case"weibull":{let k=p.shape,th=p.scale,v=x<0?0:(k/th)*Math.pow(x/th,k-1)*Math.exp(-Math.pow(x/th,k)),c=x<0?0:1-Math.exp(-Math.pow(x/th,k)),m=th*gamma(1+1/k),vv=th*th*(gamma(1+2/k)-Math.pow(gamma(1+1/k),2));return{v,c,m,vv,range:[0,th*4],discrete:false}}
case"lognormal":{let m=p.mu,s=p.sigma,v=x<=0?0:Math.exp(-.5*((Math.log(x)-m)/s)**2)/(x*s*Math.sqrt(2*Math.PI)),c=x<=0?0:normalCdf(Math.log(x),m,s);return{v,c,m:Math.exp(m+s*s/2),vv:(Math.exp(s*s)-1)*Math.exp(2*m+s*s),range:[.001,Math.exp(m+4*s)],discrete:false}}
case"cauchy":{let x0=p.x0,g=p.gamma,v=1/(Math.PI*g*(1+((x-x0)/g)**2)),c=.5+Math.atan((x-x0)/g)/Math.PI;return{v,c,m:NaN,vv:NaN,range:[x0-10*g,x0+10*g],discrete:false}}
case"t":{let v=p.df,z=x,den=tPdf(z,v),c=.5+Math.sign(z)*integrateCDF(t=>tPdf(t,v),Math.abs(z),0);return{v:den,c,m:v>1?0:NaN,vv:v>2?v/(v-2):NaN,range:[-5,5],discrete:false}}
case"f":{let d1=p.df1,d2=p.df2,v=fPdf(x,d1,d2),c=integrateCDF(z=>fPdf(z,d1,d2),x,0);return{v,c,m:d2>2?d2/(d2-2):NaN,vv:NaN,range:[.001,5],discrete:false}}
case"chisq":{let k=p.df,v=gammaPdf(x,k/2,2),c=integrateCDF(z=>gammaPdf(z,k/2,2),x,0);return{v,c,m:k,vv:2*k,range:[0,k+6*Math.sqrt(2*k)],discrete:false}}
case"logistic":{let m=p.mu,s=p.s,v=Math.exp(-(x-m)/s)/(s*Math.pow(1+Math.exp(-(x-m)/s),2)),c=1/(1+Math.exp(-(x-m)/s));return{v,c,m,vv:Math.PI*Math.PI*s*s/3,range:[m-8*s,m+8*s],discrete:false}}
case"laplace":{let m=p.mu,b=p.b,v=Math.exp(-Math.abs(x-m)/b)/(2*b),c=x<m?.5*Math.exp((x-m)/b):1-.5*Math.exp(-(x-m)/b);return{v,c,m,vv:2*b*b,range:[m-8*b,m+8*b],discrete:false}}
case"pareto":{let xm=p.xm,a=p.alpha,v=x<xm?0:a*Math.pow(xm,a)/Math.pow(x,a+1),c=x<xm?0:1-Math.pow(xm/x,a);return{v,c,m:a>1?a*xm/(a-1):NaN,vv:a>2?a*xm*xm/((a-1)**2*(a-2)):NaN,range:[xm,xm*15],discrete:false}}
case"rayleigh":{let s=p.sigma,v=x<0?0:x/(s*s)*Math.exp(-x*x/(2*s*s)),c=x<0?0:1-Math.exp(-x*x/(2*s*s));return{v,c,m:s*Math.sqrt(Math.PI/2),vv:(4-Math.PI)*s*s/2,range:[0,4*s],discrete:false}}
case"gumbel":{let m=p.mu,b=p.beta,z=(x-m)/b,e=Math.exp(-z),v=Math.exp(-(z+e))/b,c=Math.exp(-e);return{v,c,m:m+.5772156649*b,vv:Math.PI*Math.PI*b*b/6,range:[m-6*b,m+8*b],discrete:false}}
case"triangular":{let a=p.a,m=p.m,b=p.b,v=x<a||x>b?0:x<=m?2*(x-a)/((b-a)*(m-a)):2*(b-x)/((b-a)*(b-m));let c=x<=a?0:x<=m?(x-a)**2/((b-a)*(m-a)):x<b?1-(b-x)**2/((b-a)*(b-m)):1;return{v,c,m:(a+m+b)/3,vv:(a*a+m*m+b*b-a*m-a*b-m*b)/18,range:[a,b],discrete:false}}
case"erlang":{let k=Math.round(p.k),l=p.lambda,th=1/l,v=gammaPdf(x,k,th),c=integrateCDF(z=>gammaPdf(z,k,th),x,0);return{v,c,m:k/l,vv:k/(l*l),range:[0,k/l+6*Math.sqrt(k/(l*l))],discrete:false}}
case"invgauss":{let m=p.mu,l=p.lambda,v=x<=0?0:Math.sqrt(l/(2*Math.PI*x**3))*Math.exp(-l*(x-m)**2/(2*m*m*x));return{v,c:NaN,m,vv:m**3/l,range:[.001,m*5],discrete:false}}
case"fisherz":return{v:normalPdf(x,0,1),c:normalCdf(x,0,1),m:0,vv:1/Math.max(1,p.df-3),range:[-4,4],discrete:false};
case"hyper":{let N=Math.round(p.N),K=Math.round(p.K),nn=Math.round(p.n),kx=Math.round(x),v=(kx<Math.max(0,nn-(N-K))||kx>Math.min(nn,K))?0:Math.exp(logChoose(K,kx)+logChoose(N-K,nn-kx)-logChoose(N,nn));let c=0;for(let i=Math.max(0,nn-(N-K));i<=Math.min(nn,K);i++)if(i<=kx)c+=Math.exp(logChoose(K,i)+logChoose(N-K,nn-i)-logChoose(N,nn));return{v,c,m:nn*K/N,vv:nn*(K/N)*(1-K/N)*(N-nn)/(N-1),range:[Math.max(0,nn-(N-K)),Math.min(nn,K)],discrete:true}}
case"duniform":{let a=Math.round(p.a),b=Math.round(p.b),kx=Math.round(x),v=kx>=a&&kx<=b?1/(b-a+1):0,c=kx<a?0:kx>=b?1:(kx-a+1)/(b-a+1);return{v,c,m:(a+b)/2,vv:((b-a+1)**2-1)/12,range:[a,b],discrete:true}}
case"categorical":{let ps=[p.p1,p.p2,p.p3],kx=Math.round(x),v=ps[kx-1]||0,c=ps.slice(0,Math.max(0,kx)).reduce((a,b)=>a+b,0);return{v,c,m:ps.reduce((a,z,i)=>a+(i+1)*z,0),vv:ps.reduce((a,z,i)=>a+(i+1)**2*z,0)-ps.reduce((a,z,i)=>a+(i+1)*z,0)**2,range:[1,3],discrete:true}}
case"multinomial":{let ps=[p.p1,p.p2,p.p3],nn=Math.round(p.n),mu=nn*ps[0],vv=nn*ps[0]*(1-ps[0]),kx=Math.round(x),v=Math.exp(logChoose(nn,kx)+kx*Math.log(ps[0])+(nn-kx)*Math.log(1-ps[0]));let c=0;for(let i=0;i<=kx;i++)c+=Math.exp(logChoose(nn,i)+i*Math.log(ps[0])+(nn-i)*Math.log(1-ps[0]));return{v,c,m:mu,vv,range:[0,nn],discrete:true}}
case"zipf":{let s=p.s,M=1000,Z=0;for(let i=1;i<=M;i++)Z+=1/Math.pow(i,s);let kx=Math.round(x),v=kx>=1&&kx<=M?1/(Math.pow(kx,s)*Z):0,c=0;for(let i=1;i<=Math.min(M,kx);i++)c+=1/(Math.pow(i,s)*Z);return{v,c,m:NaN,vv:NaN,range:[1,Math.min(50,M)],discrete:true}}
case"logarithmic":{let pp=p.p,kx=Math.round(x),v=kx>=1?-(1/Math.log(1-pp))*Math.pow(pp,kx)/kx:0,c=0;for(let i=1;i<=Math.min(500,kx);i++)c+=-(1/Math.log(1-pp))*Math.pow(pp,i)/i;return{v,c,m:pp/((pp-1)*Math.log(1-pp)),vv:NaN,range:[1,Math.max(20,Math.ceil(10/Math.max(.05,1-pp)))],discrete:true}}
case"skellam":{let a=p.mu1,b=p.mu2,kx=Math.round(x),v=Math.exp(-(a+b))*Math.pow(a/b,kx/2)*besseli(Math.abs(kx),2*Math.sqrt(a*b)),c=0;for(let i=-30;i<=kx;i++)c+=Math.exp(-(a+b))*Math.pow(a/b,i/2)*besseli(Math.abs(i),2*Math.sqrt(a*b));return{v,c:Math.max(0,Math.min(1,c)),m:a-b,vv:a+b,range:[Math.floor(a-b-6*Math.sqrt(a+b)),Math.ceil(a-b+6*Math.sqrt(a+b))],discrete:true}}
case"dlaplace":{let pp=p.p,kx=Math.round(x),v=(1-pp)/(1+pp)*Math.pow(pp,Math.abs(kx)),c=0;for(let i=-50;i<=kx;i++)c+=(1-pp)/(1+pp)*Math.pow(pp,Math.abs(i));return{v,c:Math.max(0,Math.min(1,c)),m:0,vv:2*pp/(1-pp)**2,range:[-20,20],discrete:true}}
case"betabin":{let nn=Math.round(p.n),a=p.alpha,b=p.beta,kx=Math.round(x),v=(kx>=0&&kx<=nn)?Math.exp(logChoose(nn,kx)+logGamma(kx+a)+logGamma(nn-kx+b)-logGamma(nn+a+b)+logGamma(a+b)-logGamma(a)-logGamma(b)):0,c=0;for(let i=0;i<=Math.min(nn,kx);i++)c+=(i>=0&&i<=nn)?Math.exp(logChoose(nn,i)+logGamma(i+a)+logGamma(nn-i+b)-logGamma(nn+a+b)+logGamma(a+b)-logGamma(a)-logGamma(b)):0;let m=nn*a/(a+b),vv=nn*a*b*(a+b+nn)/((a+b)**2*(a+b+1));return{v,c,m,vv,range:[0,nn],discrete:true}}
case"dirichletmulti":{let nn=Math.round(p.n),a=p.a1,b=p.a2,c0=p.a3,A=a+b+c0,kx=Math.round(x),v=(kx>=0&&kx<=nn)?Math.exp(logChoose(nn,kx)+logGamma(kx+a)+logGamma(nn-kx+b+c0)-logGamma(nn+A)+logGamma(A)-logGamma(a)-logGamma(b+c0)):0;return{v,c:NaN,m:nn*a/A,vv:nn*(a/A)*(1-a/A)*(A+nn)/(A+1),range:[0,nn],discrete:true}}
case"borel":{let l=p.lambda,kx=Math.round(x),v=kx>=1?Math.exp(-l*kx)*Math.pow(l*kx,kx-1)/gamma(kx+1):0;return{v,c:NaN,m:1/(1-l),vv:l/(1-l)**3,range:[1,Math.max(20,Math.ceil(10/(1-l)))],discrete:true}}
case"yulesimon":{let rr=p.rho,kx=Math.round(x),v=kx>=1?rr*Math.exp(logGamma(kx)+logGamma(rr+1)-logGamma(kx+rr+1)):0;return{v,c:NaN,m:rr/(rr-1),vv:rr**2/((rr-1)**2*(rr-2)),range:[1,30],discrete:true}}
case"benford":{let base=Math.round(p.base),d=Math.round(x),v=d>=1&&d<base?Math.log(1+1/d)/Math.log(base):0,c=0;for(let i=1;i<=Math.min(d,base-1);i++)c+=Math.log(1+1/i)/Math.log(base);return{v,c,m:NaN,vv:NaN,range:[1,base-1],discrete:true}}
case"bipoisson":{let l=p.l1+p.l3,kx=Math.round(x),v=poissonPmf(kx,l),c=0;for(let i=0;i<=kx;i++)c+=poissonPmf(i,l);return{v,c,m:l,vv:l,range:[0,Math.max(10,Math.ceil(l+6*Math.sqrt(l)))],discrete:true}}
case"crp":{let nn=Math.round(p.n),al=p.alpha,m=0;for(let i=1;i<=nn;i++)m+=al/(al+i-1);return{v:NaN,c:NaN,m,vv:NaN,range:[1,nn],discrete:true}}
default:return{v:NaN,c:NaN,m:NaN,vv:NaN,range:[-5,5],discrete:false}
}}

function fmt(v){return Number.isFinite(v)?v.toPrecision(8):"Undefined"}
function numericMoments(spec,p){
  const key=spec.key;
  const oldFast=FAST_MATH; FAST_MATH=true;
  // Closed-form moments for the distributions where they are standard and stable.
  let m=NaN,v=NaN,sk=NaN,ex=NaN,med=NaN,mode=NaN;
  const q=p.p??0, n=Math.round(p.n??10), r=Math.round(p.r??4), lam=p.lambda??3;
  switch(key){
    case "bernoulli": m=q; v=q*(1-q); sk=(v>0)?(1-2*q)/Math.sqrt(v):NaN; ex=(v>0)?(1-6*q*(1-q))/v:NaN; med=q<.5?0:q>.5?1:.5; mode=q<.5?0:q>.5?1:"0 and 1"; break;
    case "binomial": m=n*q; v=n*q*(1-q); sk=v? (1-2*q)/Math.sqrt(v):NaN; ex=v? (1-6*q*(1-q))/v:NaN; med=Math.floor(n*q+0.5); mode=(q===0?0:q===1?n:Math.floor((n+1)*q)); break;
    case "geometric": m=1/q; v=(1-q)/(q*q); sk=(2-q)/Math.sqrt(1-q); ex=6+(q*q)/(1-q); med=Math.ceil(-Math.log(2)/Math.log(1-q)); mode=1; break;
    case "negbin": m=r/q; v=r*(1-q)/(q*q); sk=(2-q)/Math.sqrt(r*(1-q)); ex=6/r+(q*q)/(r*(1-q)); med=Math.floor(r/q); mode=Math.floor((r-1)/q); break;
    case "poisson": m=lam; v=lam; sk=1/Math.sqrt(lam); ex=1/lam; med=Math.floor(lam+1/3-0.02/lam); mode=Math.floor(lam); break;
    case "duniform": {let a=p.a,b=p.b; m=(a+b)/2; v=((b-a+1)**2-1)/12; sk=0; ex=-6/5*( ((b-a+1)**2+1)/((b-a+1)**2-1) ); med=(a+b)/2; mode="all integers"; break;}
    case "uniform": {let a=p.a,b=p.b; m=(a+b)/2; v=(b-a)**2/12; sk=0; ex=-6/5; med=m; mode="all x∈[a,b]"; break;}
    case "normal": m=p.mu; v=p.sigma**2; sk=0; ex=0; med=m; mode=m; break;
    case "exponential": m=1/lam; v=1/lam**2; sk=2; ex=6; med=Math.log(2)/lam; mode=0; break;
    case "gamma": {let a=p.shape,th=p.scale; m=a*th; v=a*th*th; sk=2/Math.sqrt(a); ex=6/a; med=a>=1?th*(a-1/3):NaN; mode=a>=1?(a-1)*th:0; break;}
    case "beta": {let a=p.alpha,b=p.beta; m=a/(a+b); v=a*b/((a+b)**2*(a+b+1)); sk=2*(b-a)*Math.sqrt(a+b+1)/((a+b+2)*Math.sqrt(a*b)); ex=6*((a-b)**2*(a+b+1)-a*b*(a+b+2))/(a*b*(a+b+2)*(a+b+3)); med=(a>1&&b>1)?(a-1/3)/(a+b-2/3):NaN; mode=(a>1&&b>1)?(a-1)/(a+b-2):(a<=1&&b>1?0:(a>1&&b<=1?1:"boundary")); break;}
    case "weibull": {let k=p.shape,th=p.scale,g1=gamma(1+1/k),g2=gamma(1+2/k),g3=gamma(1+3/k),g4=gamma(1+4/k); m=th*g1; v=th*th*(g2-g1*g1); sk=(g3-3*g1*g2+2*g1**3)/Math.pow(g2-g1*g1,1.5); ex=(g4-4*g1*g3+6*g1*g1*g2-3*g1**4)/(g2-g1*g1)**2-3; med=th*Math.pow(Math.log(2),1/k); mode=k>=1?th*Math.pow((k-1)/k,1/k):0; break;}
    case "lognormal": {let a=p.mu,s=p.sigma; m=Math.exp(a+s*s/2); v=(Math.exp(s*s)-1)*Math.exp(2*a+s*s); sk=(Math.exp(s*s)+2)*Math.sqrt(Math.exp(s*s)-1); ex=Math.exp(4*s*s)+2*Math.exp(3*s*s)+3*Math.exp(2*s*s)-6; med=Math.exp(a); mode=Math.exp(a-s*s); break;}
    case "cauchy": med=p.x0; mode=p.x0; break;
    case "t": {let df=p.df; med=0; mode=0; if(df>1)m=0;if(df>2)v=df/(df-2);if(df>3)sk=0;if(df>4)ex=6/(df-4);break;}
    case "f": {let d1=p.df1,d2=p.df2; if(d2>2)m=d2/(d2-2); if(d2>4)v=2*d2*d2*(d1+d2-2)/(d1*(d2-2)**2*(d2-4)); if(d2>6)sk=(2*d1+d2-2)*Math.sqrt(8*(d2-4))/( (d2-6)*Math.sqrt(d1*(d1+d2-2)) ); if(d2>8)ex=12*(5*d2-22)*(d1+d2-2)+d1*(d2-4)*(d2-6)*(d2-8); break;}
    case "chisq": {let df=p.df; m=df; v=2*df; sk=Math.sqrt(8/df); ex=12/df; med=df*Math.pow(1-2/(9*df),3); mode=Math.max(df-2,0); break;}
    case "logistic": {let a=p.mu,s=p.s; m=a; v=Math.PI**2*s*s/3; sk=0; ex=6/5; med=a; mode=a; break;}
    case "laplace": {let a=p.mu,b=p.b; m=a; v=2*b*b; sk=0; ex=3; med=a; mode=a; break;}
    case "pareto": {let xm=p.xm,a=p.alpha; if(a>1)m=a*xm/(a-1); if(a>2)v=a*xm*xm/((a-1)**2*(a-2)); if(a>3)sk=2*(1+a)*Math.sqrt(a-2)/(a-3)*Math.sqrt(1/a); if(a>4)ex=6*(a**3+a**2-6*a-2)/(a*(a-3)*(a-4)); med=xm*Math.pow(2,1/a); mode=xm; break;}
    case "rayleigh": {let sig=p.sigma; m=sig*Math.sqrt(Math.PI/2); v=(4-Math.PI)*sig*sig/2; sk=2*Math.sqrt(Math.PI)*(Math.PI-3)/(4-Math.PI)**1.5; ex=(6*Math.PI**2-24*Math.PI+16)/(4-Math.PI)**2-3; med=sig*Math.sqrt(2*Math.log(2)); mode=sig; break;}
    case "gumbel": {let a=p.mu,b=p.beta; m=a+0.5772156649*b; v=Math.PI**2*b*b/6; sk=12*Math.sqrt(6)*1.202056903/(Math.PI**3); ex=12/5; med=a-b*Math.log(Math.log(2)); mode=a; break;}
    case "triangular": {let a=p.a,c=p.m,b=p.b; m=(a+b+c)/3; v=(a*a+b*b+c*c-a*b-a*c-b*c)/18; sk=7*Math.sqrt(2)*(a+b-2*c)*(2*a-b-c)*(a-2*b+c)/(5*Math.pow(a*a+b*b+c*c-a*b-a*c-b*c,1.5)); ex=NaN; med=c>= (a+b)/2 ? a+Math.sqrt((b-a)*(c-a)/2) : b-Math.sqrt((b-a)*(b-c)/2); mode=c; break;}
    case "erlang": {let k=Math.round(p.k),l=p.lambda; m=k/l; v=k/(l*l); sk=2/Math.sqrt(k); ex=6/k; med=(k-1/3)/l; mode=(k-1)/l; break;}
    case "invgauss": {let mu=p.mu,la=p.lambda; m=mu; v=mu**3/la; sk=3*Math.sqrt(mu/la); ex=15*mu/la; med=mu*(Math.sqrt(1+9*mu*mu/(4*la*la))-3*mu/(2*la)); mode=mu*(Math.sqrt(1+9*mu*mu/(4*la*la))-3*mu/(2*la)); break;}
    case "fisherz": {m=0;v=1;sk=0;ex=0;med=0;mode=0;break;}
    default: break;
  }
  // Numerical fallback for raw/central moments. This also covers distributions whose simple formulas are not implemented above.
  const range=calcCore(spec.key,0,p).range||[-5,5];
  let lo=range[0],hi=range[1]; if(!Number.isFinite(lo))lo=-10;if(!Number.isFinite(hi))hi=10;if(hi<=lo){lo=-5;hi=5}
  let pts=[], probs=[];
  if(spec.type==="Discrete"){
    let a=Math.ceil(lo),b=Math.floor(hi); if(b-a>5000)b=a+5000;
    for(let x=a;x<=b;x++){let z=calcCore(spec.key,x,p).v;if(Number.isFinite(z)&&z>0){pts.push(x);probs.push(z)}}
  }else{
    let N=500, dx=(hi-lo)/N; for(let i=0;i<=N;i++){let x=lo+i*dx,z=calcCore(spec.key,x,p).v;if(Number.isFinite(z)&&z>=0){pts.push(x);probs.push(z*(i===0||i===N?0.5:1)*dx)}}
  }
  let total=probs.reduce((a,b)=>a+b,0); if(total>0){probs=probs.map(z=>z/total);if(!Number.isFinite(m))m=pts.reduce((a,x,i)=>a+x*probs[i],0);if(!Number.isFinite(v)){let c=m;v=pts.reduce((a,x,i)=>a+(x-c)**2*probs[i],0)}
    let raw=[1,2,3,4].map(k=>pts.reduce((a,x,i)=>a+x**k*probs[i],0));let c2=pts.reduce((a,x,i)=>a+(x-m)**2*probs[i],0),c3=pts.reduce((a,x,i)=>a+(x-m)**3*probs[i],0),c4=pts.reduce((a,x,i)=>a+(x-m)**4*probs[i],0);
    if(!Number.isFinite(sk)&&c2>0)sk=c3/Math.pow(c2,1.5); if(!Number.isFinite(ex)&&c2>0)ex=c4/(c2*c2)-3;
    if(!Number.isFinite(med)){let acc=0;for(let i=0;i<probs.length;i++){acc+=probs[i];if(acc>=.5){med=pts[i];break}}}
    if(!Number.isFinite(mode)){let im=probs.indexOf(Math.max(...probs));mode=pts[im]}
    FAST_MATH=oldFast; return {mean:m,variance:v,sd:Math.sqrt(Math.max(0,v)),median:med,mode,raw,central:[0,c2,c3,c4],skew:sk,excess:ex};
  }
  FAST_MATH=oldFast; return {mean:m,variance:v,sd:Number.isFinite(v)?Math.sqrt(Math.max(0,v)):NaN,median:med,mode,raw:[m,NaN,NaN,NaN],central:[0,v,NaN,NaN],skew:sk,excess:ex};
}
const LAWS={
"Bernoulli":{law:"P(X=x)=p^x(1-p)^{1-x},  x∈{0,1}",support:"0<p<1; X is the success indicator."},
"Binomial":{law:"P(X=x)=C(n,x)p^x(1-p)^{n-x},  x=0,1,…,n",support:"n=1,2,…; 0<p<1."},
"Geometric":{law:"P(X=x)=p(1-p)^{x-1},  x=1,2,…",support:"This site uses the trials-until-first-success parameterization."},
"Negative Binomial":{law:"P(X=x)=C(x+r-1,x)p^r(1-p)^x,  x=0,1,…",support:"X counts failures before the r-th success."},
"Hypergeometric":{law:"P(X=x)=[C(K,x)C(N-K,n-x)]/C(N,n)",support:"N population, K successes, n draws without replacement."},
"Poisson":{law:"P(X=x)=e^{-λ}λ^x/x!,  x=0,1,…",support:"λ>0."},
"Discrete Uniform":{law:"P(X=x)=1/(b-a+1),  x=a,a+1,…,b",support:"a and b are integers with a≤b."},
"Categorical":{law:"P(X=i)=p_i,  i=1,…,k;  Σp_i=1",support:"Each outcome is a category."},
"Multinomial":{law:"P(X_1=x_1,…,X_k=x_k)=n!/(∏x_i!)∏p_i^{x_i}",support:"Σx_i=n and Σp_i=1."},
"Zipf":{law:"P(X=k)=k^{-s}/ζ(s),  k=1,2,…",support:"s>1; ζ(s) is the Riemann zeta function."},
"Logarithmic":{law:"P(X=k)=-p^k/[k ln(1-p)],  k=1,2,…",support:"0<p<1."},
"Skellam":{law:"P(X=k)=e^{-(μ_1+μ_2)}(μ_1/μ_2)^{k/2}I_{|k|}(2√(μ_1μ_2))",support:"Difference of two independent Poisson variables."},
"Discrete Laplace":{law:"P(X=k)=(1-p)/(1+p)·p^{|k|},  k∈ℤ",support:"0<p<1."},
"Beta-Binomial":{law:"P(X=x)=C(n,x)B(x+α,n-x+β)/B(α,β)",support:"x=0,…,n; α,β>0."},
"Dirichlet-Multinomial":{law:"P(X=x)=n!/∏x_i! · Γ(α_0)/Γ(n+α_0) · ∏Γ(x_i+α_i)/Γ(α_i)",support:"α_0=Σα_i and Σx_i=n."},
"Borel":{law:"P(X=k)=e^{-λk}(λk)^{k-1}/k!,  k=1,2,…",support:"0<λ≤1."},
"Yule-Simon":{law:"P(X=k)=ρ·B(k,ρ+1),  k=1,2,…",support:"ρ>0."},
"Benford":{law:"P(D=d)=log_{10}(1+1/d),  d=1,…,9",support:"Leading digit distribution in base 10."},
"Bivariate Poisson":{law:"X=U+W,  Y=V+W with U,V,W independent Poisson",support:"Parameters λ1, λ2, λ3>0."},
"Chinese Restaurant Process":{law:"P(new table at customer i)=α/(α+i-1)",support:"α>0; this defines the seating process rather than a single univariate PMF."},
"Uniform":{law:"f(x)=1/(b-a),  a≤x≤b; 0 otherwise",support:"a<b."},
"Normal":{law:"f(x)=1/(σ√(2π)) exp[-(x-μ)^2/(2σ^2)],  -∞<x<∞",support:"σ>0."},
"Exponential":{law:"f(x)=λe^{-λx},  x≥0; 0 otherwise",support:"λ>0."},
"Gamma":{law:"f(x)=x^{α-1}e^{-x/θ}/[Γ(α)θ^α],  x>0",support:"Shape α>0 and scale θ>0."},
"Beta":{law:"f(x)=x^{α-1}(1-x)^{β-1}/B(α,β),  0<x<1",support:"α,β>0."},
"Weibull":{law:"f(x)=(k/λ)(x/λ)^{k-1}e^{-(x/λ)^k},  x≥0",support:"Shape k>0, scale λ>0."},
"Lognormal":{law:"f(x)=1/(xσ√(2π)) exp[-(ln x-μ)^2/(2σ^2)],  x>0",support:"σ>0; ln(X)~N(μ,σ²)."},
"Cauchy":{law:"f(x)=1/[πγ(1+((x-x_0)/γ)^2)],  -∞<x<∞",support:"γ>0."},
"Student's t":{law:"f(x)=Γ((ν+1)/2)/[√(νπ)Γ(ν/2)]·(1+x²/ν)^{-(ν+1)/2}",support:"ν>0."},
"F":{law:"f(x)=((d_1x)^{d_1}d_2^{d_2}/(d_1x+d_2)^{d_1+d_2})^{1/2}/[xB(d_1/2,d_2/2)]",support:"x>0; d_1,d_2>0."},
"Chi-Square":{law:"f(x)=x^{ν/2-1}e^{-x/2}/[2^{ν/2}Γ(ν/2)],  x>0",support:"ν>0 degrees of freedom."},
"Logistic":{law:"f(x)=e^{-(x-μ)/s}/[s(1+e^{-(x-μ)/s})²]",support:"s>0."},
"Laplace":{law:"f(x)=exp(-|x-μ|/b)/(2b)",support:"b>0."},
"Pareto":{law:"f(x)=αx_m^α/x^{α+1},  x≥x_m",support:"α>0, x_m>0."},
"Rayleigh":{law:"f(x)=xe^{-x²/(2σ²)}/σ²,  x≥0",support:"σ>0."},
"Gumbel":{law:"f(x)=exp[-(z+e^{-z})]/β,  z=(x-μ)/β",support:"β>0; maximum-type Gumbel."},
"Triangular":{law:"f(x)=2(x-a)/[(b-a)(m-a)] for a≤x≤m; 2(b-x)/[(b-a)(b-m)] for m≤x≤b",support:"a≤m≤b."},
"Erlang":{law:"f(x)=λ^k x^{k-1}e^{-λx}/(k-1)!,  x≥0",support:"k is a positive integer; λ>0."},
"Inverse Gaussian":{law:"f(x)=√[λ/(2πx³)] exp[-λ(x-μ)²/(2μ²x)],  x>0",support:"μ>0, λ>0."},
"Fisher's z":{law:"z=atanh(r)=1/2 ln[(1+r)/(1-r)]",support:"For a sample correlation r, Fisher's transform is approximately N(atanh(ρ), 1/(n-3)) under standard conditions."}
};
function calculateDist(){let spec=distSpec(),p=getParams(),x=Number(document.getElementById("xval")?.value);if(!Number.isFinite(x))x=spec.type==="Discrete"?0:(p.mu??p.a??0);let r=calcCore(spec.key,x,p);document.getElementById("pmf").textContent=fmt(r.v);document.getElementById("cdf").textContent=fmt(r.c);let M=numericMoments(spec,p);document.getElementById("mean").textContent=fmt(M.mean);document.getElementById("variance").textContent=fmt(M.variance);document.getElementById("median").textContent=fmt(M.median);document.getElementById("mode").textContent=typeof M.mode==="string"?M.mode:fmt(M.mode);document.getElementById("raw1").textContent=fmt(M.raw[0]);document.getElementById("raw2").textContent=fmt(M.raw[1]);document.getElementById("raw3").textContent=fmt(M.raw[2]);document.getElementById("raw4").textContent=fmt(M.raw[3]);document.getElementById("central1").textContent=fmt(M.central[0]);document.getElementById("central2").textContent=fmt(M.central[1]);document.getElementById("central3").textContent=fmt(M.central[2]);document.getElementById("central4").textContent=fmt(M.central[3]);document.getElementById("skewness").textContent=fmt(M.skew);document.getElementById("kurtosis").textContent=fmt(Number.isFinite(M.excess)?M.excess+3:NaN);document.getElementById("excessKurtosis").textContent=fmt(M.excess);document.getElementById("sd").textContent=fmt(M.sd);drawPlot(spec,p,r.range)}
function setupDist(){let spec=distSpec(),box=document.getElementById("fields");if(!box)return;document.getElementById("distTitle").textContent=spec.name;document.getElementById("typeTitle").textContent=spec.type+" distribution";const L=LAWS[spec.name]||{law:"Law not available",support:"Please verify the parameterization before using this distribution."};document.getElementById("lawBox").textContent=L.law;document.getElementById("lawSupport").textContent=L.support;let labels=spec.params.split(",");box.innerHTML=labels.map(p=>`<div class="field"><label>${p}</label><input data-p="${p}" value="${defaults[p]??1}"></div>`).join("")+`<div class="field"><label>x</label><input id="xval" value="${spec.type==="Discrete"?1:0}"></div>`;document.getElementById("calcBtn").onclick=calculateDist;document.getElementById("resetBtn").onclick=()=>setupDist();document.getElementById("note").textContent=spec.type==="Discrete"?"PMF, CDF, mean, median, mode, first four raw moments, first four central moments, skewness and excess kurtosis are shown where defined.":"PDF, CDF, mean, median, mode, first four raw moments, first four central moments, skewness and excess kurtosis are shown where defined.";calculateDist()}
function drawPlot(spec,p,range){const oldFast=FAST_MATH; FAST_MATH=true;let c=document.getElementById("plot"),ctx=c.getContext("2d"),W=c.width,H=c.height;ctx.clearRect(0,0,W,H);let lo=range[0],hi=range[1];if(!Number.isFinite(lo)||!Number.isFinite(hi)||lo===hi){lo=-5;hi=5}let pad=45;ctx.strokeStyle="#9aa9bc";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(pad,H-pad);ctx.lineTo(W-pad,H-pad);ctx.moveTo(pad,20);ctx.lineTo(pad,H-pad);ctx.stroke();let vals=[];for(let i=0;i<=300;i++){let x=lo+(hi-lo)*i/300;let r=calcCore(spec.key,x,p);vals.push([x,Number.isFinite(r.v)?Math.max(0,r.v):0])}let ymax=Math.max(...vals.map(v=>v[1]),1e-8)*1.12;ctx.strokeStyle="#2563eb";ctx.lineWidth=3;ctx.beginPath();vals.forEach(([x,y],i)=>{let px=pad+(x-lo)/(hi-lo)*(W-2*pad),py=H-pad-y/ymax*(H-55);if(i===0)ctx.moveTo(px,py);else ctx.lineTo(px,py)});ctx.stroke();ctx.fillStyle="#526176";ctx.font="14px Segoe UI";ctx.fillText(lo.toPrecision(4),pad,H-18);ctx.fillText(hi.toPrecision(4),W-pad-35,H-18);ctx.fillText("x",W-25,H-pad+5);ctx.fillText(spec.type==="Discrete"?"PMF":"PDF",pad+10,28); FAST_MATH=oldFast}
if(location.pathname.endsWith("distribution.html"))setupDist();
if(document.getElementById("distGrid")&&document.getElementById("search")){
function filterD(){const q=document.getElementById("search").value.toLowerCase(),t=document.getElementById("type").value;document.getElementById("distGrid").innerHTML=D.filter(d=>(t==="all"||d.type===t)&&d.name.toLowerCase().includes(q)).map(d=>`<a class="dist-card" href="distribution.html?name=${encodeURIComponent(d.name)}"><h4>${d.name}</h4><small>${d.type} distribution</small></a>`).join("")}
document.getElementById("search").addEventListener("input",filterD);document.getElementById("type").addEventListener("change",filterD);
}


/* ---------- Bivariate Analysis ---------- */
function biTokens(v){return String(v||'').trim().split(/[\s,;\n\t]+/).filter(Boolean)}
function biNum(v){let a=biTokens(v), n=a.map(Number);return a.length===n.length && a.length>0 && n.every(Number.isFinite)}
function biNumeric(v){return biTokens(v).map(Number).filter(Number.isFinite)}
function biCategorical(v){return biTokens(v)}
function biFmt(x){return Number.isFinite(x)?(Math.abs(x)<1e-10?'0':x.toFixed(5)):'—'}
function biMean(a){return a.reduce((s,x)=>s+x,0)/a.length}
function biVariance(a){let m=biMean(a);return a.length>1?a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1):NaN}
function biPearson(x,y){let mx=biMean(x),my=biMean(y),sx=0,sy=0,c=0;for(let i=0;i<x.length;i++){let dx=x[i]-mx,dy=y[i]-my;c+=dx*dy;sx+=dx*dx;sy+=dy*dy}return c/Math.sqrt(sx*sy)}
function biRank(a){let idx=a.map((v,i)=>[v,i]).sort((u,v)=>u[0]-v[0]),r=Array(a.length),i=0;while(i<a.length){let j=i;while(j+1<a.length&&idx[j+1][0]===idx[i][0])j++;let av=(i+j+2)/2;for(let k=i;k<=j;k++)r[idx[k][1]]=av;i=j+1}return r}
function biSpearman(x,y){return biPearson(biRank(x),biRank(y))}
function biRegression(x,y){let mx=biMean(x),my=biMean(y),sxx=0,sxy=0;for(let i=0;i<x.length;i++){sxx+=(x[i]-mx)**2;sxy+=(x[i]-mx)*(y[i]-my)}let b=sxy/sxx,a=my-b*mx,r=biPearson(x,y);return{a,b,r,r2:r*r}}
function biGroups(a){let m=new Map();a.forEach(v=>m.set(v,(m.get(v)||0)+1));return [...m.entries()].sort((x,y)=>String(x[0]).localeCompare(String(y[0]),undefined,{numeric:true}))}
function biChiSquare(a,b){let rows=[...new Set(a)],cols=[...new Set(b)],obs=rows.map(r=>cols.map(c=>{let n=0;for(let i=0;i<a.length;i++)if(a[i]===r&&b[i]===c)n++;return n}));let rt=obs.map(r=>r.reduce((s,x)=>s+x,0)),ct=cols.map((_,j)=>obs.reduce((s,r)=>s+r[j],0)),N=a.length,chi=0;for(let i=0;i<rows.length;i++)for(let j=0;j<cols.length;j++){let e=rt[i]*ct[j]/N;if(e>0)chi+=(obs[i][j]-e)**2/e}return{chi,df:(rows.length-1)*(cols.length-1),rows,cols,obs}}
function biErf(x){return erf(x)}
function biNormalP(z){return .5*(1+biErf(z/Math.sqrt(2)))}
function biTApproxP(t,df){let z=Math.abs(t);if(df>100)return 2*(1-biNormalP(z));let x=df/(df+z*z);let a=df/2,b=.5;function ibeta(xx,aa,bb){let bt=xx===0||xx===1?0:Math.exp(logGamma(aa+bb)-logGamma(aa)-logGamma(bb)+aa*Math.log(xx)+bb*Math.log(1-xx));function cf(x,a,b){let qab=a+b,qap=a+1,qam=a-1,c=1,d=1-qab*x/qap;if(Math.abs(d)<1e-30)d=1e-30;d=1/d;let h=d;for(let m=1;m<=200;m++){let m2=2*m,aa1=m*(b-m)*x/((qam+m2)*(a+m2)),aa2=-(a+m)*(qab+m)*x/((a+m2)*(qap+m2));d=1+aa1*d;if(Math.abs(d)<1e-30)d=1e-30;c=1+aa1/c;if(Math.abs(c)<1e-30)c=1e-30;d=1/d;h*=d*c;d=1+aa2*d;if(Math.abs(d)<1e-30)d=1e-30;c=1+aa2/c;if(Math.abs(c)<1e-30)c=1e-30;d=1/d;let del=d*c;h*=del;if(Math.abs(del-1)<3e-7)break}return h}if(xx<(aa+1)/(aa+bb+2))return bt*cf(xx,aa,bb)/aa;return 1-bt*cf(1-xx,bb,aa)/bb}let tail=.5*ibeta(x,a,b);return Math.min(1,2*tail)}
function biTTest(x,y){let d=x.map((v,i)=>v-y[i]),m=biMean(d),s=Math.sqrt(biVariance(d)),t=m/(s/Math.sqrt(d.length)),df=d.length-1;return{t,df,p:biTApproxP(t,df)}}
function biBuildTable(ch){let html='<table class="bi-table"><thead><tr><th></th>'+ch.cols.map(c=>`<th>${c}</th>`).join('')+'</tr></thead><tbody>';ch.rows.forEach((r,i)=>{html+=`<tr><th>${r}</th>${ch.obs[i].map(v=>`<td>${v}</td>`).join('')}</tr>`});return html+'</tbody></table>'}

function biFreqTable(a,name){let g=biGroups(a),N=a.length;return `<div class="bi-section"><h4>📋 Frequency Table — ${name}</h4><table class="bi-table"><thead><tr><th>Value / Category</th><th>Frequency</th><th>Relative Frequency</th><th>Percentage</th></tr></thead><tbody>${g.map(([v,c])=>`<tr><td>${v}</td><td>${c}</td><td>${biFmt(c/N)}</td><td>${biFmt(c*100/N)}%</td></tr>`).join('')}</tbody></table></div>`}
function biScatter(x,y,n1,n2){let W=760,H=430,pad=58,cw=W-2*pad,ch=H-2*pad,xmin=Math.min(...x),xmax=Math.max(...x),ymin=Math.min(...y),ymax=Math.max(...y);if(xmax===xmin){xmin-=1;xmax+=1}if(ymax===ymin){ymin-=1;ymax+=1}let sx=v=>pad+(v-xmin)/(xmax-xmin)*cw,sy=v=>H-pad-(v-ymin)/(ymax-ymin)*ch;let pts=x.map((v,i)=>`${sx(v).toFixed(1)},${sy(y[i]).toFixed(1)}`).join(' ');let xTicks=5,yTicks=5;let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Scatter plot"><rect x="0" y="0" width="${W}" height="${H}" fill="transparent"/>`;for(let i=0;i<=xTicks;i++){let v=xmin+(xmax-xmin)*i/xTicks,px=sx(v);svg+=`<line x1="${px}" y1="${pad}" x2="${px}" y2="${H-pad}" class="bi-gridline"/><text x="${px}" y="${H-pad+22}" text-anchor="middle" class="bi-axistext">${biFmt(v)}</text>`}for(let i=0;i<=yTicks;i++){let v=ymin+(ymax-ymin)*i/yTicks,py=sy(v);svg+=`<line x1="${pad}" y1="${py}" x2="${W-pad}" y2="${py}" class="bi-gridline"/><text x="${pad-10}" y="${py+4}" text-anchor="end" class="bi-axistext">${biFmt(v)}</text>`}svg+=`<line x1="${pad}" y1="${H-pad}" x2="${W-pad}" y2="${H-pad}" class="bi-axis"/><line x1="${pad}" y1="${pad}" x2="${pad}" y2="${H-pad}" class="bi-axis"/><polyline points="${pts}" fill="none" stroke="none"/>`;x.forEach((v,i)=>{svg+=`<circle cx="${sx(v)}" cy="${sy(y[i])}" r="5" class="bi-point"><title>${n1}: ${v}, ${n2}: ${y[i]}</title></circle>`});svg+=`<text x="${W/2}" y="${H-10}" text-anchor="middle" class="bi-label">${n1}</text><text x="16" y="${H/2}" text-anchor="middle" transform="rotate(-90 16 ${H/2})" class="bi-label">${n2}</text></svg>`;return `<div class="bi-section"><h4>📈 Scatter Plot</h4><div class="bi-chart-wrap">${svg}</div></div>`}
function biVisualize(t1,t2,tok1,tok2,n1,n2){let v='';v+=biFreqTable(tok1,n1)+biFreqTable(tok2,n2);if(t1==='Numerical'&&t2==='Numerical')v+=biScatter(tok1.map(Number),tok2.map(Number),n1,n2);return v}

window.runBivariate=function(){let n1=document.getElementById('biName1')?.value.trim()||'Variable 1',n2=document.getElementById('biName2')?.value.trim()||'Variable 2',raw1=document.getElementById('biData1')?.value||'',raw2=document.getElementById('biData2')?.value||'',tok1=biTokens(raw1),tok2=biTokens(raw2);let out=document.getElementById('biResult'),det=document.getElementById('biDetected'),vis=document.getElementById('biVisuals');if(tok1.length<2||tok2.length<2){det.innerHTML='<span class="bi-warn">Please enter at least two observations for each variable.</span>';out.innerHTML='';if(vis)vis.innerHTML='';return}if(tok1.length!==tok2.length){det.innerHTML='<span class="bi-warn">Both variables must have the same number of observations. Variable 1 has '+tok1.length+' and Variable 2 has '+tok2.length+'.</span>';out.innerHTML='';if(vis)vis.innerHTML='';return}let t1=biNum(raw1)?'Numerical':'Categorical',t2=biNum(raw2)?'Numerical':'Categorical';det.innerHTML=`<b>Detected:</b> ${n1} → ${t1} &nbsp; | &nbsp; ${n2} → ${t2} &nbsp; | &nbsp; n = ${tok1.length}`;let html='';
if(t1==='Numerical'&&t2==='Numerical'){let x=tok1.map(Number),y=tok2.map(Number),r=biPearson(x,y),rs=biSpearman(x,y),cov=x.length>1?x.reduce((s,v,i)=>s+(v-biMean(x))*(y[i]-biMean(y)),0)/(x.length-1):NaN,reg=biRegression(x,y);html+=`<div class="bi-section"><h4>📌 Applicable analyses: Numerical × Numerical</h4><div class="bi-grid"><div class="bi-stat"><span>Pearson correlation (r)</span><strong>${biFmt(r)}</strong></div><div class="bi-stat"><span>Spearman correlation (ρ)</span><strong>${biFmt(rs)}</strong></div><div class="bi-stat"><span>Covariance</span><strong>${biFmt(cov)}</strong></div><div class="bi-stat"><span>R²</span><strong>${biFmt(reg.r2)}</strong></div></div></div><div class="bi-section"><h4>📈 Simple Linear Regression</h4><div class="bi-grid"><div class="bi-stat"><span>Intercept (a)</span><strong>${biFmt(reg.a)}</strong></div><div class="bi-stat"><span>Slope (b)</span><strong>${biFmt(reg.b)}</strong></div><div class="bi-stat"><span>Equation</span><strong>${n2} = ${biFmt(reg.a)} + ${biFmt(reg.b)}×${n1}</strong></div></div></div><div class="bi-note">For this pair, correlation, rank correlation, covariance and simple linear regression are applicable. A scatter plot can be added to the visualization section next.</div>`}
else if(t1==='Categorical'&&t2==='Categorical'){let a=tok1,b=tok2,ch=biChiSquare(a,b),phi=Math.sqrt(ch.chi/a.length),htmlTable=biBuildTable(ch);html+=`<div class="bi-section"><h4>📌 Applicable analyses: Categorical × Categorical</h4><h4>Cross-tabulation</h4>${htmlTable}<div class="bi-grid" style="margin-top:10px"><div class="bi-stat"><span>Chi-square (χ²)</span><strong>${biFmt(ch.chi)}</strong></div><div class="bi-stat"><span>Degrees of freedom</span><strong>${ch.df}</strong></div><div class="bi-stat"><span>Cramer's V</span><strong>${biFmt(Math.sqrt(ch.chi/(a.length*Math.min(ch.rows.length-1,ch.cols.length-1))))}</strong></div><div class="bi-stat"><span>Phi (when 2×2)</span><strong>${ch.rows.length===2&&ch.cols.length===2?biFmt(phi):'N/A'}</strong></div></div></div><div class="bi-note">For this pair, cross-tabulation, Chi-square test of independence and association measures are applicable.</div>`}
else{let cat=t1==='Categorical'?tok1:tok2,num=t1==='Numerical'?tok1.map(Number):tok2.map(Number),groups=biGroups(cat),summary=groups.map(([g])=>{let vals=num.filter((_,i)=>cat[i]===g);return [g,vals.length,biMean(vals),Math.sqrt(biVariance(vals))]});html+=`<div class="bi-section"><h4>📌 Applicable analyses: Categorical × Numerical</h4><table class="bi-table"><thead><tr><th>Group</th><th>n</th><th>Mean</th><th>SD</th></tr></thead><tbody>${summary.map(r=>`<tr>${r.map((v,i)=>`<td>${i>1?biFmt(v):v}</td>`).join('')}</tr>`).join('')}</tbody></table><div class="bi-grid" style="margin-top:10px"><div class="bi-stat"><span>Number of groups</span><strong>${groups.length}</strong></div><div class="bi-stat"><span>Overall mean</span><strong>${biFmt(biMean(num))}</strong></div></div></div><div class="bi-note">For this pair, group-wise descriptive statistics and boxplot/group comparison are applicable. Independent t-test is appropriate when there are exactly 2 groups; one-way ANOVA is appropriate when there are 3 or more groups.</div>`}
out.innerHTML=html;if(vis)vis.innerHTML=biVisualize(t1,t2,tok1,tok2,n1,n2)}
function loadBiExample(){document.getElementById('biName1').value='Study Hours';document.getElementById('biName2').value='Marks';document.getElementById('biData1').value='2,3,4,5,6,7,8,9';document.getElementById('biData2').value='45,50,58,65,72,78,84,90';runBivariate()}
if(document.getElementById('biData1'))runBivariate();


/* ---------- Bivariate Analysis v12 enhancements ---------- */
function biPill(p){return Number.isFinite(p)?(p<0.001?'p < 0.001':'p = '+biFmt(p)): 'p = —'}
function biSig(p){return Number.isFinite(p)&&p<0.05?'Significant at 5% level':'Not significant at 5% level'}
function biFormula(title,formula,desc){return `<details class="bi-formula"><summary>📐 ${title} — Show Formula / Law</summary><div class="bi-formula-body"><div class="formula-box">${formula}</div>${desc?`<p>${desc}</p>`:''}</div></details>`}
function biPearsonP(r,n){if(n<3||Math.abs(r)>=1)return Math.abs(r)>=1?0:NaN;let t=Math.abs(r)*Math.sqrt((n-2)/(1-r*r));return biTApproxP(t,n-2)}
function biGammaP(a,x){if(x<0||a<=0)return NaN;if(x===0)return 1;let gln=logGamma(a),sum=1/a,del=sum,ap=a;for(let i=1;i<=200;i++){ap++;del*=x/ap;sum+=del;if(Math.abs(del)<Math.abs(sum)*3e-8)break}let P=sum*Math.exp(-x+a*Math.log(x)-gln);if(x<a+1)return 1-P;let b=x+1-a,c=1/1e-300,d=1/b,h=d;for(let i=1;i<=200;i++){let an=-i*(i-a),bn=b+2*i;d=an*d+bn;if(Math.abs(d)<1e-300)d=1e-300;c=bn+an/c;if(Math.abs(c)<1e-300)c=1e-300;d=1/d;let del2=d*c;h*=del2;if(Math.abs(del2-1)<3e-8)break}let Q=Math.exp(-x+a*Math.log(x)-gln)*h;return Q}
function biChiP(chi,df){return biGammaP(df/2,chi/2)}
function biIBeta(x,a,b){if(x<=0)return 0;if(x>=1)return 1;let bt=Math.exp(logGamma(a+b)-logGamma(a)-logGamma(b)+a*Math.log(x)+b*Math.log(1-x));function cf(xx,aa,bb){let qab=aa+bb,qap=aa+1,qam=aa-1,c=1,d=1-qab*xx/qap;if(Math.abs(d)<1e-30)d=1e-30;d=1/d;let h=d;for(let m=1;m<=200;m++){let m2=2*m,aa1=m*(bb-m)*xx/((qam+m2)*(aa+m2)),aa2=-(aa+m)*(qab+m)*xx/((aa+m2)*(qap+m2));d=1+aa1*d;if(Math.abs(d)<1e-30)d=1e-30;c=1+aa1/c;if(Math.abs(c)<1e-30)c=1e-30;d=1/d;h*=d*c;d=1+aa2*d;if(Math.abs(d)<1e-30)d=1e-30;c=1+aa2/c;if(Math.abs(c)<1e-30)c=1e-30;d=1/d;let del=d*c;h*=del;if(Math.abs(del-1)<3e-8)break}return h}if(x<(a+1)/(a+b+2))return bt*cf(x,a,b)/a;return 1-bt*cf(1-x,b,a)/b}
function biFP(f,d1,d2){if(!Number.isFinite(f)||f<0)return NaN;let z=(d1*f)/(d1*f+d2);return 1-biIBeta(z,d1/2,d2/2)}
function biIndependentT(groups){let a=groups[0],b=groups[1],na=a.length,nb=b.length,ma=biMean(a),mb=biMean(b),va=biVariance(a),vb=biVariance(b);let sp2=((na-1)*va+(nb-1)*vb)/(na+nb-2),se=Math.sqrt(sp2*(1/na+1/nb)),t=(ma-mb)/se,df=na+nb-2;return{t,df,p:biTApproxP(t,df),ma,mb,va,vb}}
function biANOVA(groups){let all=groups.flat(),grand=biMean(all),k=groups.length,N=all.length,ssb=0,ssw=0;groups.forEach(g=>{let m=biMean(g);ssb+=g.length*(m-grand)**2;ssw+=g.reduce((s,v)=>s+(v-m)**2,0)});let df1=k-1,df2=N-k,msb=ssb/df1,msw=ssw/df2,F=msb/msw;return{ssb,ssw,df1,df2,msb,msw,F,p:biFP(F,df1,df2)}}
function biBoxplot(groups,names){let W=760,H=360,pad=60, all=groups.flat(), ymin=Math.min(...all),ymax=Math.max(...all);if(ymin===ymax){ymin-=1;ymax+=1}let sy=v=>H-pad-(v-ymin)/(ymax-ymin)*(H-2*pad);let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Boxplot">`;for(let i=0;i<=5;i++){let v=ymin+(ymax-ymin)*i/5,y=sy(v);svg+=`<line x1="${pad}" y1="${y}" x2="${W-25}" y2="${y}" class="bi-gridline"/><text x="${pad-10}" y="${y+4}" text-anchor="end" class="bi-axistext">${biFmt(v)}</text>`}let slot=(W-pad-25)/Math.max(1,groups.length);groups.forEach((g,idx)=>{let a=[...g].sort((x,y)=>x-y),q1=biQuantile(a,.25),med=biQuantile(a,.5),q3=biQuantile(a,.75),iqr=q3-q1,lo=Math.max(a[0],q1-1.5*iqr),hi=Math.min(a[a.length-1],q3+1.5*iqr),x=pad+slot*(idx+.5),bw=Math.min(70,slot*.45);svg+=`<line x1="${x}" y1="${sy(hi)}" x2="${x}" y2="${sy(lo)}" class="bi-axis"/><line x1="${x-bw/3}" y1="${sy(hi)}" x2="${x+bw/3}" y2="${sy(hi)}" class="bi-axis"/><line x1="${x-bw/3}" y1="${sy(lo)}" x2="${x+bw/3}" y2="${sy(lo)}" class="bi-axis"/><rect x="${x-bw/2}" y="${sy(q3)}" width="${bw}" height="${Math.max(2,sy(q1)-sy(q3))}" class="bi-box"/><line x1="${x-bw/2}" y1="${sy(med)}" x2="${x+bw/2}" y2="${sy(med)}" class="bi-median"/><text x="${x}" y="${H-20}" text-anchor="middle" class="bi-axistext">${names[idx]}</text>`});svg+='</svg>';return `<div class="bi-chart-wrap">${svg}</div>`}
function biQuantile(a,q){if(!a.length)return NaN;let pos=(a.length-1)*q,lo=Math.floor(pos),hi=Math.ceil(pos);return lo===hi?a[lo]:a[lo]+(a[hi]-a[lo])*(pos-lo)}
function biScatter(x,y,n1,n2,reg){let W=760,H=430,pad=58,cw=W-2*pad,ch=H-2*pad,xmin=Math.min(...x),xmax=Math.max(...x),ymin=Math.min(...y),ymax=Math.max(...y);if(xmax===xmin){xmin-=1;xmax+=1}if(ymax===ymin){ymin-=1;ymax+=1}let sx=v=>pad+(v-xmin)/(xmax-xmin)*cw,sy=v=>H-pad-(v-ymin)/(ymax-ymin)*ch;let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Scatter plot">`;for(let i=0;i<=5;i++){let vx=xmin+(xmax-xmin)*i/5,px=sx(vx),vy=ymin+(ymax-ymin)*i/5,py=sy(vy);svg+=`<line x1="${px}" y1="${pad}" x2="${px}" y2="${H-pad}" class="bi-gridline"/><text x="${px}" y="${H-pad+22}" text-anchor="middle" class="bi-axistext">${biFmt(vx)}</text><line x1="${pad}" y1="${py}" x2="${W-pad}" y2="${py}" class="bi-gridline"/><text x="${pad-10}" y="${py+4}" text-anchor="end" class="bi-axistext">${biFmt(vy)}</text>`}svg+=`<line x1="${pad}" y1="${H-pad}" x2="${W-pad}" y2="${H-pad}" class="bi-axis"/><line x1="${pad}" y1="${pad}" x2="${pad}" y2="${H-pad}" class="bi-axis"/>`;x.forEach((v,i)=>svg+=`<circle cx="${sx(v)}" cy="${sy(y[i])}" r="5" class="bi-point"><title>${n1}: ${v}, ${n2}: ${y[i]}</title></circle>`);if(reg&&Number.isFinite(reg.b)){let x1=xmin,x2=xmax,y1=reg.a+reg.b*x1,y2=reg.a+reg.b*x2;svg+=`<line x1="${sx(x1)}" y1="${sy(y1)}" x2="${sx(x2)}" y2="${sy(y2)}" class="bi-regline"/>`}svg+=`<text x="${W/2}" y="${H-10}" text-anchor="middle" class="bi-label">${n1}</text><text x="16" y="${H/2}" text-anchor="middle" transform="rotate(-90 16 ${H/2})" class="bi-label">${n2}</text></svg>`;return `<div class="bi-section"><h4>📈 Scatter Plot + Regression Line</h4><div class="bi-chart-wrap">${svg}</div></div>`}
function biMatrix(data,headers){let nums=headers.map((_,j)=>data.map(r=>Number(r[j])));let h='<div class="bi-section"><h4>🔢 Correlation Matrix</h4><table class="bi-table"><thead><tr><th></th>'+headers.map(h=>`<th>${h}</th>`).join('')+'</tr></thead><tbody>';headers.forEach((name,i)=>{h+=`<tr><th>${name}</th>`+headers.map((_,j)=>`<td>${i===j?'1.00000':biFmt(biPearson(nums[i],nums[j]))}</td>`).join('')+'</tr>';});return h+'</tbody></table></div>'}
function biControls(){return `<div class="bi-report-actions"><button class="btn secondary" onclick="printBiReport()">🖨️ Print / Save PDF</button><button class="btn secondary" onclick="exportBiCSV()">⬇️ Export Results CSV</button></div>`}
function biRenderFormulaSet(type,n1,n2){if(type==='nn')return biFormula('Pearson Correlation',`r = \frac{n\sum xy-\sum x\sum y}{\sqrt{[n\sum x^2-(\sum x)^2][n\sum y^2-(\sum y)^2]}}`,'Measures the strength and direction of a linear relationship.')+biFormula('Spearman Rank Correlation',`\\rho = 1-\\frac{6\\sum d^2}{n(n^2-1)}`,'Uses ranks and is useful for monotonic relationships or ordinal data.')+biFormula('Covariance',`\\operatorname{Cov}(X,Y)=\\frac{\\sum (x_i-\\bar x)(y_i-\\bar y)}{n-1}`)+biFormula('Simple Linear Regression',`Y=a+bX,\\quad b=\\frac{\\sum(x-\\bar x)(y-\\bar y)}{\\sum(x-\\bar x)^2},\\quad a=\\bar y-b\\bar x`)+biFormula('Coefficient of Determination',`R^2=r^2`);if(type==='cc')return biFormula('Chi-square Test',`\\chi^2=\\sum\\frac{(O-E)^2}{E},\\quad E=\\frac{(Row\\ Total)(Column\\ Total)}{Grand\\ Total}`)+biFormula("Cramer's V",`V=\\sqrt{\\frac{\\chi^2}{n(k-1)}}`)+biFormula('Phi Coefficient',`\\phi=\\sqrt{\\frac{\\chi^2}{n}}`);return biFormula('Independent Samples t-test',`t=\\frac{\\bar X_1-\\bar X_2}{s_p\\sqrt{1/n_1+1/n_2}},\\quad df=n_1+n_2-2`)+biFormula('One-way ANOVA',`F=\\frac{MS_{Between}}{MS_{Within}}`)+biFormula('Group Mean',`\\bar X=\\frac{\\sum X}{n}`)}
function biExportText(){let out=document.getElementById('biResult')?.innerText||'',vis=document.getElementById('biVisuals')?.innerText||'';return out+'\n\n'+vis}
function exportBiCSV(){let text=biExportText().split('\n').filter(Boolean).map(x=>'"'+x.replaceAll('"','""')+'"').join('\n');let blob=new Blob([text],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='bivariate_analysis_results.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function printBiReport(){let n1=document.getElementById('biName1')?.value||'Variable 1',n2=document.getElementById('biName2')?.value||'Variable 2',body=document.getElementById('biResult')?.innerHTML||'';let vis=document.getElementById('biVisuals')?.innerHTML||'';let w=window.open('','_blank');if(!w)return;w.document.write(`<html><head><title>Bivariate Analysis Report</title><style>body{font-family:Arial,sans-serif;padding:30px;color:#172033}table{border-collapse:collapse;width:100%;margin:12px 0}th,td{border:1px solid #ddd;padding:7px}h1{font-size:22px}h4{margin-bottom:8px}.bi-section{margin:18px 0}.formula-box{font-size:20px;padding:12px;background:#f6f8fb;border-radius:8px}.bi-formula-body{display:block}.bi-chart-wrap{max-width:760px}.bi-chart-wrap svg{width:100%}</style></head><body><h1>Bivariate Analysis Report</h1><p><b>${n1}</b> × <b>${n2}</b></p>${body}${vis}<p>Generated by Statistical Hub.</p></body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),300)}
function handleBiFile(input){let f=input.files?.[0];if(!f)return;let ext=f.name.toLowerCase().split('.').pop();if(ext==='csv'){let r=new FileReader();r.onload=()=>biLoadMatrix(String(r.result));r.readAsText(f)}else if(window.XLSX){let r=new FileReader();r.onload=e=>{let wb=XLSX.read(new Uint8Array(e.target.result),{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:''});biLoadMatrix(rows.map(r=>r.join(',')).join('\n'))};r.readAsArrayBuffer(f)}else alert('XLSX reader is unavailable. Please use CSV.')}
function biLoadMatrix(text){let lines=String(text).trim().split(/\r?\n/).filter(Boolean),rows=lines.map(l=>l.split(/,(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)/).map(v=>v.trim().replace(/^"|"$/g,'')));if(rows.length<2)return;let headers=rows[0],data=rows.slice(1);if(headers.length>=2){document.getElementById('biName1').value=headers[0];document.getElementById('biName2').value=headers[1];document.getElementById('biData1').value=data.map(r=>r[0]??'').join(',');document.getElementById('biData2').value=data.map(r=>r[1]??'').join(',');runBivariate()}if(headers.length>=3&&data.every(r=>headers.every((_,i)=>Number.isFinite(Number(r[i]))))){let area=document.getElementById('biVisuals');if(area)area.insertAdjacentHTML('afterbegin',biMatrix(data,headers))}}

/* ---------- Correlation option-based analysis (v13) ---------- */
function biIsBinary(a){let u=[...new Set(a.map(String))];return u.length===2}
function biIsOrdinal(a){return a.every(v=>String(v).trim()!=="")}
function biCountPairs(a,b){let c=0;for(let i=0;i<a.length;i++)if(a[i]!==b[i])c++;return c}
function biKendall(x,y){let C=0,D=0,T=0,U=0;for(let i=0;i<x.length;i++){for(let j=i+1;j<x.length;j++){let dx=x[j]-x[i],dy=y[j]-y[i];if(dx===0&&dy===0)continue;if(dx===0){T++;continue}if(dy===0){U++;continue}if(dx*dy>0)C++;else D++;}}let den=Math.sqrt((C+D+T)*(C+D+U));return den?((C-D)/den):NaN}
function biGamma(a,b){let C=0,D=0;for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++){let dx=String(a[i])===String(a[j])?0:(String(a[i])>String(a[j])?1:-1),dy=String(b[i])===String(b[j])?0:(String(b[i])>String(b[j])?1:-1);if(dx*dy>0)C++;else if(dx*dy<0)D++;}return C+D?(C-D)/(C+D):NaN}
function biSomersD(a,b){let C=0,D=0,Ty=0;for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++){let dx=String(a[i])===String(a[j])?0:(String(a[i])>String(a[j])?1:-1),dy=String(b[i])===String(b[j])?0:(String(b[i])>String(b[j])?1:-1);if(dx*dy>0)C++;else if(dx*dy<0)D++;else if(dx!==0&&dy===0)Ty++;}return C+D+Ty?(C-D)/(C+D+Ty):NaN}
function biBinaryCoding(a){let u=[...new Set(a.map(String))];return a.map(v=>u.indexOf(String(v))===1?1:0)}
function biPointBiserial(num,bin){let codes=biBinaryCoding(bin),g0=num.filter((_,i)=>codes[i]===0),g1=num.filter((_,i)=>codes[i]===1),s=Math.sqrt(biVariance(num)),p=g1.length/num.length,q=1-p;return s?p>0&&q>0?((biMean(g1)-biMean(g0))/s)*Math.sqrt(p*q):NaN:NaN}
function biPhi(a,b){return biPearson(biBinaryCoding(a),biBinaryCoding(b))}
function biNormPdf(z){return Math.exp(-0.5*z*z)/Math.sqrt(2*Math.PI)}
function biNormInv(p){
 if(p<=0||p>=1)return NaN;
 let a=[-39.6968302866538,220.946098424521,-275.928510446969,138.357751867269,-30.6647980661472,2.50662827745924],b=[-54.4760987982241,161.585836858041,-155.698979859887,66.8013118877197,-13.2806815528857],c=[-0.00778489400243029,-0.322396458041136,-2.40075827716184,-2.54973253934373,4.37466414146497,2.93816398269878],d=[0.00778469570904146,0.32246712907004,2.445134137143,3.75440866190742];
 let pl=.02425,ph=1-pl,q,r;
 if(p<pl){q=Math.sqrt(-2*Math.log(p));let num=((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5];let den=(((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1;return num/den}
 if(p>ph){q=Math.sqrt(-2*Math.log(1-p));let num=((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5];let den=(((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1;return -num/den}
 q=p-.5;r=q*q;let num=((((((a[0]*r+a[1])*r+a[2])*r+a[3])*r+a[4])*r+a[5])*q);let den=(((((b[0]*r+b[1])*r+b[2])*r+b[3])*r+b[4])*r+1);return num/den;
}
function biBiserial(num,bin){let codes=biBinaryCoding(bin),p=codes.filter(v=>v===1).length/num.length,q=1-p;if(!(p>0&&q>0))return NaN;let rpb=biPointBiserial(num,bin),cut=biNormInv(q),y=biNormPdf(cut);return rpb*Math.sqrt(p*q)/y}
function biFormulaCard(title,formula,desc,value,p,extra=''){return `<div class="bi-result-card"><h4>${title}</h4>${Number.isFinite(value)?`<div class="bi-result-value">${biFmt(value)}</div>`:''}<div class="formula-box math-formula">\(${formula}\)</div>${desc?`<p class="bi-note">${desc}</p>`:''}${extra}${Number.isFinite(p)?`<p class="bi-p"><b>p-value:</b> ${biFmt(p)} &nbsp; <b>${biSig(p)}</b></p>`:''}</div>`}
function biOption(name,key,subtitle){return `<button type="button" class="bi-analysis-option" data-corr="${key}" onclick="showCorrelation('${key}')"><b>${name}</b><small>${subtitle||''}</small></button>`}
let BI_CURRENT={};
function biRefreshMath(el){if(window.MathJax?.typesetPromise)window.MathJax.typesetPromise([el]).catch(()=>{});}
function showCorrelation(key){let r=document.getElementById('biSelectedResult');if(!r)return;let {x,y,n1,n2,t1,t2}=BI_CURRENT;let html='';
 if(key==='pearson'){let v=biPearson(x,y),p=biPearsonP(v,x.length);html=biFormulaCard("Pearson's Product-Moment Correlation (r)",`r=\\frac{n\\sum xy-\\sum x\\sum y}{\\sqrt{[n\\sum x^2-(\\sum x)^2][n\\sum y^2-(\\sum y)^2]}}`,`Measures the strength and direction of a linear relationship between two numerical variables.`,v,p)}
 else if(key==='spearman'){let v=biSpearman(x,y),p=biPearsonP(v,x.length);html=biFormulaCard("Spearman's Rank Correlation (ρ)",`\\rho=1-\\frac{6\\sum d^2}{n(n^2-1)}`,`Ranks both variables and measures a monotonic relationship. Ties are handled by average ranks.`,v,p)}
 else if(key==='kendall'){let v=biKendall(x,y);html=biFormulaCard("Kendall's Tau (τ)",`\\tau_b=\\frac{C-D}{\\sqrt{(C+D+T_x)(C+D+T_y)}}`,`Based on concordant and discordant pairs; suitable for ordinal/rank data and ties.`,v)}
 else if(key==='gamma'){let v=biGamma(x,y);html=biFormulaCard("Goodman–Kruskal's Gamma (γ)",`\\gamma=\\frac{C-D}{C+D}`,`Ordinal association based on concordant and discordant pairs; tied pairs are ignored.`,v)}
 else if(key==='somers'){let v=biSomersD(x,y);html=biFormulaCard("Somers' D",`D_{Y\\mid X}=\\frac{C-D}{C+D+T_Y}`,`Directional ordinal association.`,v)}
 else if(key==='pointbiserial'){let num=t1==='Numerical'?x:y,bin=t1==='Categorical'?x:y,v=biPointBiserial(num,bin);html=biFormulaCard("Point-Biserial Correlation (rₚᵦ)",`r_{pb}=\\frac{\\bar X_1-\\bar X_0}{s_X}\\sqrt{pq}`,`Applicable to one continuous variable and one binary variable.`,v)}
 else if(key==='phi'){let v=biPhi(x,y);html=biFormulaCard("Phi Coefficient (φ)",`\\phi=\\frac{ad-bc}{\\sqrt{(a+b)(c+d)(a+c)(b+d)}}`,`Applicable when both variables are binary.`,v)}
 else if(key==='biserial'){let num=t1==='Numerical'?x:y,bin=t1==='Categorical'?x:y,v=biBiserial(num,bin);html=biFormulaCard("Biserial Correlation (r_b)",`r_b=r_{pb}\\frac{\\sqrt{pq}}{y}`,`Used when a continuous variable has been artificially divided into two groups.`,v)}
 else if(key==='polyserial'){html=biFormulaCard("Polyserial Correlation (rₚₛ)",`r_{ps}=\\frac{\\operatorname{Cov}(X,Z)}{\\sigma_X\\sigma_Z}`,`Estimates correlation between a continuous variable and an underlying latent continuous variable represented by ordinal categories. Full estimation uses maximum likelihood.`)}
 else if(key==='polychoric'){html=biFormulaCard("Polychoric Correlation (rₚc)",`r_{pc}=\\hat{\\rho}\\text{ from the bivariate-normal latent-variable likelihood}`,`Used for two ordinal variables assumed to arise from underlying continuous latent variables. Full estimation requires threshold estimation and maximum likelihood.`)}
 else if(key==='regression'){let g=biRegression(x,y),sxx=x.reduce((s,v)=>s+(v-biMean(x))**2,0),se=Math.sqrt(((y.reduce((s,v,i)=>s+(v-(g.a+g.b*x[i]))**2,0))/(x.length-2))/sxx),t=g.b/se,p=biTApproxP(t,x.length-2);let extra=`<div class="bi-regression-grid"><div><span>Intercept (b₀)</span><strong>${biFmt(g.a)}</strong></div><div><span>Slope (b₁)</span><strong>${biFmt(g.b)}</strong></div><div><span>R²</span><strong>${biFmt(g.r2)}</strong></div><div><span>t for slope</span><strong>${biFmt(t)}</strong></div></div><div class="bi-model"><b>Regression model:</b> ${n2} = ${biFmt(g.a)} + ${biFmt(g.b)} × ${n1}</div>`;html=biFormulaCard('Simple Linear Regression',`\\hat Y=a+bX,\\quad b=\\frac{\\sum(x-\\bar x)(y-\\bar y)}{\\sum(x-\\bar x)^2},\\quad a=\\bar y-b\\bar x`,`Predicts ${n2} from ${n1}.`,g.b,p,extra)}
 else if(key==='r2'){let v=biPearson(x,y)**2;html=biFormulaCard('Coefficient of Determination (R²)',`R^2=r^2`,`Proportion of variation in the outcome explained by the linear relationship.`,v)}
 else if(key==='scatter'){html=biScatter(x,y,n1,n2)}
 else if(key==='frequency1'){html=biFreqTable(x,n1)}
 else if(key==='frequency2'){html=biFreqTable(y,n2)}
 else if(key==='crosstab'){let ch=biChiSquare(x,y);html=`<div class="bi-result-card"><h4>Cross-tabulation</h4>${biBuildTable(ch)}<div class="formula-box math-formula">\\(E=\\frac{(Row\\ Total)(Column\\ Total)}{Grand\\ Total}\\)</div></div>`}
 r.innerHTML=html;biRefreshMath(r);r.scrollIntoView({behavior:'smooth',block:'nearest'});
}
function biApplicableOptions(t1,t2,tok1,tok2){let out=[];let bothNum=t1==='Numerical'&&t2==='Numerical', bothCat=t1==='Categorical'&&t2==='Categorical', oneNum=(t1==='Numerical'&&t2==='Categorical')||(t2==='Numerical'&&t1==='Categorical'), bin1=biIsBinary(tok1),bin2=biIsBinary(tok2);
 if(bothNum){out.push(biOption("Pearson's Product-Moment (r)",'pearson','Linear relationship'));out.push(biOption("Spearman's Rank (ρ)",'spearman','Rank / monotonic relationship'));out.push(biOption("Kendall's Tau (τ)",'kendall','Rank concordance'));out.push(biOption('Simple Linear Regression','regression','Model, coefficients and R²'));out.push(biOption('Coefficient of Determination (R²)','r2','Explained variation'));out.push(biOption('Scatter Plot','scatter','X–Y relationship'));}
 if(bothCat){out.push(biOption("Kendall's Tau (τ)",'kendall','Ordinal association'));out.push(biOption("Goodman–Kruskal's Gamma (γ)",'gamma','Ordinal association'));out.push(biOption("Somers' D",'somers','Directional ordinal association'));if(bin1&&bin2)out.push(biOption('Phi Coefficient (φ)','phi','Binary × binary'));out.push(biOption('Cross-tabulation','crosstab','Observed frequencies'));}
 if(oneNum){let num=t1==='Numerical'?tok1.map(Number):tok2.map(Number),cat=t1==='Categorical'?tok1:tok2;if(biIsBinary(cat))out.push(biOption('Point-Biserial (rₚᵦ)','pointbiserial','Continuous × binary'));out.push(biOption('Biserial (rᵦ)','biserial','Artificial dichotomy'));out.push(biOption('Polyserial (rₚₛ)','polyserial','Continuous × ordinal'));}
 if(bothCat&&!bin1&&!bin2)out.push(biOption('Polychoric (rₚc)','polychoric','Ordinal × ordinal'));
 out.push(biOption(`Frequency Table — ${t1==='Numerical'?'Variable 1':'Variable 1'}`,'frequency1','Frequency, relative frequency and %'));out.push(biOption('Frequency Table — Variable 2','frequency2','Frequency, relative frequency and %'));
 return out.join('')}
window.runBivariate=function(){let n1=document.getElementById('biName1')?.value.trim()||'Variable 1',n2=document.getElementById('biName2')?.value.trim()||'Variable 2',raw1=document.getElementById('biData1')?.value||'',raw2=document.getElementById('biData2')?.value||'',tok1=biTokens(raw1),tok2=biTokens(raw2),out=document.getElementById('biResult'),det=document.getElementById('biDetected');if(!out||!det)return;if(tok1.length<2||tok2.length<2){det.innerHTML='<span class="bi-warn">Please enter at least two observations for each variable.</span>';out.innerHTML='';return}if(tok1.length!==tok2.length){det.innerHTML='<span class="bi-warn">Both variables must have the same number of observations.</span>';out.innerHTML='';return}let t1=biNum(raw1)?'Numerical':'Categorical',t2=biNum(raw2)?'Numerical':'Categorical',x=t1==='Numerical'?tok1.map(Number):tok1,y=t2==='Numerical'?tok2.map(Number):tok2;BI_CURRENT={x,y,n1,n2,t1,t2};det.innerHTML=`<b>Detected:</b> ${n1} → ${t1} &nbsp; | &nbsp; ${n2} → ${t2} &nbsp; | &nbsp; n = ${tok1.length}<br><small>Choose an applicable tool below. Results appear only after you click a tool.</small>`;let opts=biApplicableOptions(t1,t2,tok1,tok2);out.innerHTML=`<div class="bi-section"><h4>🔗 Applicable Tools</h4><div class="bi-options">${opts}</div><div id="biSelectedResult" class="bi-selected-result"><p class="bi-note">No result is shown automatically. Click a tool above.</p></div></div>`;biRefreshMath(out)};
if(document.getElementById('biData1'))window.runBivariate();
